// vue_jd/demo/src/components/Login.vue
<template>
    <div class="login_wrap">
        <p class="title">用户登录</p>
        <form action="http://localhost:4001/admin/login" class="login_form" method="post">
            <input class="login_username" type="text" placeholder="请输入账号" name="username" v-model="value">
            <input class="login_password" type="password" placeholder="请输入密码" name="password" v-model="pass">
          <input type="button"  class="login_submit" @click="fun1(value,pass)" value="登录" >
        </form>
    </div>
</template>
<script>
import $ from 'jquery'
export default {
    name:'Login',
    data:function(){
        return{
            value:null,
            pass:null
        }
    },
    watch: {
        value:function(oldValue){
            this.value=oldValue
        },
        pass:function(oldValue){
            this.pass=oldValue
        }
    },
    methods:{
        fun1:function(username,password){
            var that =this
           $.ajax({
               url:'http://localhost:4001/admin/login',
               type:'post',
               data:{
                  username:username,
                  password:password
               },
               success:function(result){
                     if(result=="登录成功"){
                      that.$router.push('/loginsucceed')
                     }
               }
           })
        },
    }
}
</script>

// react_jd/demo/src/components/login.js
import React,{Component} from 'react';
import $ from 'jquery'

class Login extends Component {
    constructor(props){
        super(props)
    }
    handleLogin(username,password){
        $.ajax({
            url:'http://localhost:4000/admin/login',
            method:'POST',
            data:{
                username:username,
                password:password,
                
            },
            success:(result)=>{
                console.log(result) 
                if(result=="ok"){
                    this.props.history.push('/succeed')
                }
            }
            
        })
    }
    render(){
         console.log(this.props)
         return(
             <div className="login_wrap">
                <form className="login_form">
                    <input type="text" name='username' id="username" placeholder="用户名"/>
                    <input type="password" name='password' id="password" placeholder="密码"/>
                    <input type="button" className="login_btn" value="登录" onClick={()=>{this.handleLogin(
                        $('#username').val(),$('#password').val()
                    )}}/>
                </form>
             </div>
         )
    }
}


export default Login
